#!/usr/bin/env bash
# ir4anki installer — backend venv + frontend build + config + systemd user
# service. Debian/Ubuntu-style Linux; requires a RUNNING desktop Anki with
# the AnkiConnect add-on (code 2055492159).
#
# Usage:
#   bash deploy/install.sh                # interactive (prompts have defaults)
#   bash deploy/install.sh --non-interactive   # accept all defaults
#   bash deploy/install.sh --no-service   # build + config only, no systemd
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$HOME/.config/ir4anki.env"
UNIT_FILE="$HOME/.config/systemd/user/ir4anki.service"
DEFAULT_STATE_DIR="$HOME/.local/state/ir4anki"

INTERACTIVE=1
WANT_SERVICE=1
for arg in "$@"; do
    case "$arg" in
        --non-interactive) INTERACTIVE=0 ;;
        --no-service) WANT_SERVICE=0 ;;
        *) echo "unknown flag: $arg" >&2; exit 2 ;;
    esac
done

say()  { printf '\n\033[1;35m== %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33mWARN: %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ask PROMPT VAR DEFAULT — read a line into VAR (DEFAULT when non-interactive
# or empty input)
ask() {
    local prompt="$1" varname="$2" default="$3" line=""
    if [ "$INTERACTIVE" -eq 1 ]; then
        printf '%s [%s]: ' "$prompt" "$default"
        read -r line || true
    fi
    if [ -n "$line" ]; then
        printf -v "$varname" '%s' "$line"
    else
        printf -v "$varname" '%s' "$default"
    fi
}

say "ir4anki installer"
echo "repo: $REPO"

# ---- 1/6 prerequisites ------------------------------------------------------
say "1/6 prerequisites"
command -v python3 >/dev/null 2>&1 || die "python3 not found (need >= 3.10)"
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' \
    || die "python3 is $(python3 -c 'import sys;print(sys.version.split()[0])'), need >= 3.10"
echo "python3 ok ($(python3 -c 'import sys;print(sys.version.split()[0])'))"

command -v node >/dev/null 2>&1 || die "node not found (need >= 18; install e.g. 'apt install nodejs npm')"
NODE_MAJOR="$(node --version | sed 's/^v\([0-9]*\).*/\1/')"
[ "$NODE_MAJOR" -ge 18 ] || die "node $(node --version), need >= 18"
command -v npm >/dev/null 2>&1 || die "npm not found"
echo "node ok ($(node --version))"

# ---- 2/6 backend venv ---------------------------------------------------------
say "2/6 backend venv + dependencies"
VENV="$REPO/backend/.venv"
if command -v uv >/dev/null 2>&1; then
    [ -d "$VENV" ] || uv venv "$VENV" --python python3
    uv pip install --python "$VENV/bin/python" -r "$REPO/backend/requirements.txt"
else
    [ -d "$VENV" ] || python3 -m venv "$VENV"
    "$VENV/bin/pip" install --upgrade pip >/dev/null
    "$VENV/bin/pip" install -r "$REPO/backend/requirements.txt"
fi
"$VENV/bin/python" -c 'import fastapi, httpx, uvicorn' || die "backend deps broken"
echo "backend deps ok"

# ---- 3/6 frontend build --------------------------------------------------------
say "3/6 frontend build (npm ci + vite build)"
cd "$REPO/frontend"
npm ci
npm run build
[ -f "$REPO/frontend/dist/index.html" ] || die "frontend build produced no dist/index.html"
echo "frontend dist ok"
cd "$REPO"

# ---- 4/6 config -------------------------------------------------------------------
say "4/6 config (~/.config/ir4anki.env)"
if [ -f "$ENV_FILE" ]; then
    echo "exists — keeping it untouched (edit by hand, then: systemctl --user restart ir4anki)"
else
    # detect Anki profiles with a collection.media dir
    MEDIA_DEFAULT=""
    ANKI2_BASE="$HOME/.local/share/Anki2"
    if [ -d "$ANKI2_BASE" ]; then
        # first profile that looks real (has collection.media)
        for d in "$ANKI2_BASE"/*/; do
            if [ -d "$d/collection.media" ]; then
                MEDIA_DEFAULT="${d}collection.media"
                break
            fi
        done
        PROFILES="$(ls -1 "$ANKI2_BASE" 2>/dev/null | tr '\n' ' ')"
        [ -n "$PROFILES" ] && echo "Anki profiles found under $ANKI2_BASE: $PROFILES"
    fi
    if [ -z "$MEDIA_DEFAULT" ]; then
        MEDIA_DEFAULT="$ANKI2_BASE/User 1/collection.media"
        warn "no Anki profile with collection.media found — using guess: $MEDIA_DEFAULT"
    fi

    ask "AnkiConnect URL" ANKICONNECT_URL "http://127.0.0.1:8765"
    ask "collection.media dir (the profile you review in)" ANKI_MEDIA_DIR "$MEDIA_DEFAULT"
    ask "state dir (round/quota/reading progress)" ANKI_STATE_DIR "$DEFAULT_STATE_DIR"
    ask "notes corpus dir (markdown, for reading mode)" ANKI_NOTES_DIR "$HOME/anki-notes"

    mkdir -p "$(dirname "$ENV_FILE")" "$ANKI_STATE_DIR" "$ANKI_NOTES_DIR"
    {
        echo "# ir4anki machine-local config — generated by deploy/install.sh on $(date -Is)"
        echo "# every knob is documented in deploy/ir4anki.env.example"
        echo "IR4ANKI_HOST=127.0.0.1"
        echo "IR4ANKI_PORT=8901"
        echo "ANKICONNECT_URL=$ANKICONNECT_URL"
        echo "ANKI_MEDIA_DIR=$ANKI_MEDIA_DIR"
        echo "ANKI_STATE_DIR=$ANKI_STATE_DIR"
        echo "ANKI_NOTES_DIR=$ANKI_NOTES_DIR"
        echo "ANKI_ROLLOVER_HOUR=4"
        echo "ANKI_PREVIEW_MODE=1"
        echo "ANKI_PREVIEW_DECK=预览池"
        echo "ANKI_PREVIEW_RELEASE_DECK=2026"
        echo "ANKI_RELEASE_DAILY_GOAL=45"
        echo "ANKI_READING_MODE=1"
        echo "ANKI_ADD_MODEL=问答题"
        echo "ANKI_ADD_CLOZE_MODEL=填空题"
    } > "$ENV_FILE"
    echo "wrote $ENV_FILE"
    [ -d "$ANKI_MEDIA_DIR" ] || warn "ANKI_MEDIA_DIR does not exist yet — card images will 404 until it does"
fi

# ---- 5/6 systemd user service -------------------------------------------------------
if [ "$WANT_SERVICE" -eq 1 ]; then
    say "5/6 systemd user service"
    if ! command -v systemctl >/dev/null 2>&1; then
        warn "systemctl not found — skipping service install"
        warn "run manually: $VENV/bin/uvicorn --app-dir $REPO/backend app:app --host 127.0.0.1 --port 8901"
    else
        mkdir -p "$(dirname "$UNIT_FILE")"
        sed "s|@REPO@|$REPO|g" "$REPO/deploy/ir4anki.service" > "$UNIT_FILE"
        systemctl --user daemon-reload
        systemctl --user enable ir4anki.service >/dev/null 2>&1
        systemctl --user restart ir4anki.service
        sleep 2
        if systemctl --user is-active --quiet ir4anki.service; then
            echo "service active"
        else
            warn "service failed to start — check: journalctl --user -u ir4anki -n 30"
        fi
        # services die on logout unless lingering is on
        if command -v loginctl >/dev/null 2>&1 && ! loginctl show-user "$USER" 2>/dev/null | grep -q 'Linger=yes'; then
            warn "user lingering is OFF: the service stops when you log out."
            warn "to keep it running: sudo loginctl enable-linger $USER"
        fi
    fi
else
    say "5/6 systemd service SKIPPED (--no-service)"
    echo "run manually: $VENV/bin/uvicorn --app-dir $REPO/backend app:app --host 127.0.0.1 --port 8901"
fi

# ---- 6/6 health ---------------------------------------------------------------------------
say "6/6 health checks"
PORT="$(grep -E '^IR4ANKI_PORT=' "$ENV_FILE" 2>/dev/null | cut -d= -f2)"
PORT="${PORT:-8901}"
HOSTURL="http://127.0.0.1:$PORT"
if "$VENV/bin/python" - "$HOSTURL" <<'PYEOF'
import sys, urllib.request
try:
    r = urllib.request.urlopen(sys.argv[1] + "/api/status", timeout=5)
    sys.exit(0 if r.status == 200 else 1)
except Exception:
    sys.exit(1)
PYEOF
then
    echo "backend responding: $HOSTURL/api/status"
else
    warn "backend not responding on $HOSTURL — if --no-service was used, start it manually first"
fi

# AnkiConnect probe (non-fatal: Anki may simply be closed right now)
ANKICONNECT="$(grep -E '^ANKICONNECT_URL=' "$ENV_FILE" 2>/dev/null | cut -d= -f2)"
ANKICONNECT="${ANKICONNECT:-http://127.0.0.1:8765}"
if "$VENV/bin/python" - "$ANKICONNECT" <<'PYEOF'
import sys, json, urllib.request
req = urllib.request.Request(
    sys.argv[1],
    data=json.dumps({"action": "version", "version": 6}).encode(),
    headers={"Content-Type": "application/json"},
)
try:
    r = json.loads(urllib.request.urlopen(req, timeout=3).read())
    sys.exit(0 if r.get("result") else 1)
except Exception:
    sys.exit(1)
PYEOF
then
    echo "AnkiConnect alive: $ANKICONNECT"
else
    warn "AnkiConnect not reachable at $ANKICONNECT — start Anki (with the AnkiConnect add-on) and the app will work"
fi

say "done"
cat <<EOF
Open the app:      $HOSTURL
Service:           systemctl --user status ir4anki
Logs:              journalctl --user -u ir4anki -f
Config:            $ENV_FILE  (restart the service after editing)
README:            $REPO/README.md

Reminder: Anki must be RUNNING (with AnkiConnect) while you use the app,
and configure Anki's own sync (AnkiWeb or self-hosted) separately.
EOF
